baseURL = 'https://saraswaminathan.com/'
languageCode = 'en-us'
title = 'Sara Swaminathan, PhD'
theme = "my-theme"
canonifyURLs = true

[params]
macyJsCDN = "https://cdn.jsdelivr.net/npm/macy@2"

[markup.goldmark.renderer]
unsafe = true

[menus]
[[menus.main]]
name = 'About Me'
pageRef = '/info'
weight = 10

[[menus.main]]
name = 'CV'
pageRef = '/cv'
weight = 20

[[menus.main]]
name = 'Art'
pageRef = '/science-illustrations'
weight = 30
